const config = {
  SERVER_PROTOCOL: "[REPLACEABLE_PROTOCOL]",
  SERVER_IP: "[REPLACEABLE_IP_ADDR]",
  SERVER_PORT: [REPLACEABLE_PORT_NUM],
  SERVER_BASE_PATH: "[REPLACEABLE_BASE_PATH]",
  BETA_MODE: false,
};

export default config;
