#!/bin/sh
set -e

echo ""
echo "  AWARE Dashboard Setup"
echo "  ─────────────────────"
echo ""

if ! command -v docker > /dev/null 2>&1; then
    echo "  Docker is required but was not found in PATH."
    echo "  Install Docker Desktop or Docker Engine, then rerun ./setup.sh."
    echo ""
    exit 1
fi

if ! sudo docker compose version > /dev/null 2>&1; then
    echo "  Docker Compose v2 is required but is not available."
    echo "  Update Docker, then rerun ./setup.sh."
    echo ""
    exit 1
fi

deploy_stack() {
    mkdir -p studies aware-micro-server/cache
    python3 setup/deploy_config.py
    sudo docker compose up --build -d
    python3 setup/init_android_tables.py --docker-prefix sudo
}

start_stack_only() {
    sudo docker compose up --build -d
    python3 setup/init_android_tables.py --docker-prefix sudo
}

wait_for_service_redirect() {
    echo "  Waiting for services to become ready for browser redirect..."

    i=0
    while [ $i -lt 180 ]; do
        if sudo docker inspect \
            -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' \
            aware_mysql aware_micro aware_configurator aware_dashboard_api aware_dashboard aware_nginx \
            2>/dev/null | awk '
                BEGIN { ok = 1 }
                $0 != "healthy" && $0 != "running" { ok = 0 }
                END { exit ok ? 0 : 1 }
            '; then
            echo "  Services are ready. Redirecting browser shortly..."
            sleep 5
            return 0
        fi

        sleep 2
        i=$((i + 1))
    done

    echo "  Services are still starting. The setup wizard will remain open."
    echo "  Run 'sudo docker compose ps' to check status."
    return 1
}

HAS_ENV=0
HAS_MICRO_CONFIG=0

if [ -f .env ]; then
    HAS_ENV=1
fi

if [ -f aware-micro-server/aware-config.json ]; then
    HAS_MICRO_CONFIG=1
fi

# If setup is already complete, offer a choice
if [ "$HAS_ENV" -eq 1 ] && [ "$HAS_MICRO_CONFIG" -eq 1 ]; then
    echo "  Existing configuration found (.env)"
    echo ""
    echo "  1) Deploy with current config"
    echo "  2) Edit configuration first"
    echo ""
    printf "  Choose [1/2]: "
    read CHOICE

    if [ "$CHOICE" = "1" ]; then
        echo ""
        echo "  Regenerating config and starting services..."
        echo ""
        deploy_stack
        echo ""
        echo "  All services are starting."
        echo "  Run 'sudo docker compose ps' to check status."
        echo "  Run 'sudo docker compose logs -f' to see logs."
        echo ""
        exit 0
    fi
elif [ "$HAS_ENV" -eq 1 ] && [ "$HAS_MICRO_CONFIG" -eq 0 ]; then
    echo "  Found .env but no aware-micro-server/aware-config.json."
    echo "  Opening the setup wizard to finish the micro-server configuration."
    echo ""
fi

# Remove markers from any previous run
rm -f .env.saved setup/.wizard_url

SUGGESTED_PUBLIC_HOST=$(python3 setup/detect_public_host.py)
printf "PUBLIC_HOST=%s\nPUBLIC_PORT=80\nPROTOCOL=http\n" "$SUGGESTED_PUBLIC_HOST" > .setup-defaults.env

# Build and start the wizard
sudo docker compose --profile setup up --build -d setup-wizard

echo ""
echo "  Waiting for setup wizard to start..."

# Wait for server.py to write the token URL (up to 30 seconds)
i=0
while [ ! -s setup/.wizard_url ] && [ $i -lt 30 ]; do
    sleep 1
    i=$((i + 1))
done

if [ ! -s setup/.wizard_url ]; then
    echo ""
    echo "  ERROR: Could not read wizard URL."
    echo "  Check logs with: sudo docker compose logs setup-wizard"
    echo ""
    exit 1
fi

TOKEN_PATH=$(cat setup/.wizard_url)
WIZARD_URL="http://${SUGGESTED_PUBLIC_HOST}:9999${TOKEN_PATH}"
echo ""
echo "  ┌──────────────────────────────────────────────────────────────┐"
echo "  │  Setup wizard is ready. Open this URL in your browser:      │"
echo "  │                                                              │"
printf "  │  %-60s  │\n" "$WIZARD_URL"
echo "  │                                                              │"
echo "  │  This token is valid for this session only.                 │"
echo "  └──────────────────────────────────────────────────────────────┘"
echo ""

# Try to open browser
if command -v xdg-open > /dev/null 2>&1; then
    xdg-open "$WIZARD_URL" 2>/dev/null &
elif command -v open > /dev/null 2>&1; then
    open "$WIZARD_URL" &
fi

echo "  Fill in the form and click Save."
echo "  Waiting for configuration..."
echo ""

# Wait for the marker file
while [ ! -f .env.saved ]; do
    sleep 2
done
rm -f .env.saved

echo "  Configuration saved! Starting services..."
echo ""

# Start the actual services using the config already generated by the wizard
start_stack_only

if wait_for_service_redirect; then
    # Stop the wizard after the browser has had time to observe readiness.
    sudo docker compose --profile setup stop setup-wizard 2>/dev/null
    sudo docker compose --profile setup rm -f setup-wizard 2>/dev/null
fi

echo ""
echo "  All services are starting."
echo "  Run 'sudo docker compose ps' to check status."
echo "  Run 'sudo docker compose logs -f' to see logs."
echo ""
