@echo off
setlocal EnableDelayedExpansion

:: Run from the directory containing setup.bat
cd /d "%~dp0"

echo.
echo   AWARE Dashboard Setup
echo   ---------------------
echo.

:: Check Docker
where docker >nul 2>&1
if errorlevel 1 (
    echo   Docker is required but was not found in PATH.
    echo   Install Docker Desktop, then rerun setup.bat.
    echo.
    exit /b 1
)

:: Check Docker Compose v2
docker compose version >nul 2>&1
if errorlevel 1 (
    echo   Docker Compose v2 is required but is not available.
    echo   Update Docker Desktop, then rerun setup.bat.
    echo.
    exit /b 1
)

:: Detect Python command (try python3, python, py)
set PYTHON=
where python3 >nul 2>&1
if not errorlevel 1 (
    set PYTHON=python3
) else (
    where python >nul 2>&1
    if not errorlevel 1 (
        set PYTHON=python
    ) else (
        where py >nul 2>&1
        if not errorlevel 1 set PYTHON=py
    )
)
if "!PYTHON!"=="" (
    echo   Python 3 is required but was not found in PATH.
    echo.
    exit /b 1
)

set HAS_ENV=0
set HAS_MICRO_CONFIG=0
if exist .env set HAS_ENV=1
if exist aware-micro-server\aware-config.json set HAS_MICRO_CONFIG=1

if "%HAS_ENV%"=="1" if "%HAS_MICRO_CONFIG%"=="1" (
    echo   Existing configuration found ^(.env^)
    echo.
    echo   1^) Deploy with current config
    echo   2^) Edit configuration first
    echo.
    set /p CHOICE=  Choose [1/2]:
    if "!CHOICE!"=="1" (
        echo.
        echo   Regenerating config and starting services...
        echo.
        call :deploy_stack
        echo.
        echo   All services are starting.
        echo   Run 'docker compose ps' to check status.
        echo   Run 'docker compose logs -f' to see logs.
        echo.
        exit /b 0
    )
    goto :wizard_flow
)

if "%HAS_ENV%"=="1" if "%HAS_MICRO_CONFIG%"=="0" (
    echo   Found .env but no aware-micro-server\aware-config.json.
    echo   Opening the setup wizard to finish the micro-server configuration.
    echo.
)

:wizard_flow
:: Remove markers from any previous run
if exist .env.saved del /f /q .env.saved
if exist setup\.wizard_url del /f /q setup\.wizard_url

:: Detect public host
set SUGGESTED_PUBLIC_HOST=localhost
for /f "delims=" %%i in ('!PYTHON! setup\detect_public_host.py') do set SUGGESTED_PUBLIC_HOST=%%i

(
    echo PUBLIC_HOST=!SUGGESTED_PUBLIC_HOST!
    echo PUBLIC_PORT=80
    echo PROTOCOL=http
)>.setup-defaults.env

:: Build and start the wizard
docker compose --profile setup up --build -d setup-wizard
if errorlevel 1 exit /b 1

echo.
echo   Waiting for setup wizard to start...

:: Wait for server.py to write the token URL (up to 30 seconds)
set /a _wi=0
:wait_wizard_url
if exist setup\.wizard_url (
    for %%f in (setup\.wizard_url) do if %%~zf gtr 0 goto :wizard_url_ready
)
set /a _wi+=1
if !_wi! geq 30 (
    echo.
    echo   ERROR: Could not read wizard URL.
    echo   Check logs with: docker compose logs setup-wizard
    echo.
    exit /b 1
)
timeout /t 1 /nobreak >nul
goto :wait_wizard_url

:wizard_url_ready
:: for/f strips CR/LF automatically
for /f "usebackq delims=" %%i in ("setup\.wizard_url") do set TOKEN_PATH=%%i
set WIZARD_URL=http://!SUGGESTED_PUBLIC_HOST!:9999!TOKEN_PATH!

echo.
echo   Setup wizard is ready. Open this URL in your browser:
echo.
echo     !WIZARD_URL!
echo.
echo   This token is valid for this session only.
echo.

start "" "!WIZARD_URL!"

echo   Fill in the form and click Save.
echo   Waiting for configuration...
echo.

:: Wait for the wizard to write config
:wait_env_saved
if exist .env.saved goto :env_saved
timeout /t 2 /nobreak >nul
goto :wait_env_saved

:env_saved
del /f /q .env.saved

echo   Configuration saved! Starting services...
echo.

:: Start the actual services using the config already generated by the wizard
docker compose up --build -d
if errorlevel 1 exit /b 1
!PYTHON! setup\init_android_tables.py

:: Keep the wizard alive until services are healthy (browser uses it to detect readiness)
call :wait_for_service_redirect
if not errorlevel 1 (
    docker compose --profile setup stop setup-wizard 2>nul
    docker compose --profile setup rm -f setup-wizard 2>nul
)

echo.
echo   All services are starting.
echo   Run 'docker compose ps' to check status.
echo   Run 'docker compose logs -f' to see logs.
echo.

exit /b 0


:deploy_stack
if not exist studies mkdir studies
if not exist aware-micro-server\cache mkdir aware-micro-server\cache
%PYTHON% setup\deploy_config.py
if errorlevel 1 exit /b 1
docker compose up --build -d
if errorlevel 1 exit /b 1
%PYTHON% setup\init_android_tables.py
exit /b 0


:wait_for_service_redirect
echo   Waiting for services to become ready for browser redirect...
set /a _hi=0
:_health_loop
%PYTHON% -c "import subprocess,sys; r=subprocess.run(['docker','inspect','-f','{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}','aware_mysql','aware_micro','aware_configurator','aware_dashboard_api','aware_dashboard','aware_nginx'],capture_output=True,text=True); lines=[l.strip() for l in r.stdout.strip().splitlines()]; ok=all(l in ('healthy','running') for l in lines) and len(lines)==6; sys.exit(0 if ok else 1)" >nul 2>&1
if not errorlevel 1 (
    echo   Services are ready. Redirecting browser shortly...
    timeout /t 5 /nobreak >nul
    exit /b 0
)
set /a _hi+=1
if !_hi! geq 90 (
    echo   Services are still starting. The setup wizard will remain open.
    echo   Run 'docker compose ps' to check status.
    exit /b 1
)
timeout /t 2 /nobreak >nul
goto :_health_loop
