"""
Django settings for aware_light_config_Django project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
import sys
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

# In Docker the whole repo is bind-mounted at /project so App01 can import the
# shared_config package that lives alongside AWARE-Configurator. Outside Docker
# there's no /project, so fall back to the repo root relative to this file.
PROJECT_ROOT = Path(os.environ.get("PROJECT_ROOT", "/project"))
if not PROJECT_ROOT.exists():
    PROJECT_ROOT = BASE_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Docker injects env vars directly via docker-compose, so this only fires for
# local (non-Docker) runs where nothing has loaded the repo-root .env yet.
if not os.environ.get("DJANGO_SECRET_KEY"):
    from shared_config.runtime import load_env

    for _key, _value in load_env(PROJECT_ROOT / ".env").items():
        os.environ.setdefault(_key, _value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.environ.get("DJANGO_SECRET_KEY", "")
if not _secret_key:
    raise RuntimeError("DJANGO_SECRET_KEY environment variable must be set")
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"


def _normalize_host(raw_value):
    value = (raw_value or "").strip()
    if not value:
        return ""
    if "://" in value:
        value = urlparse(value).hostname or ""
    elif value.startswith("[") and "]" in value:
        value = value[1:value.index("]")]
    elif value.count(":") == 1:
        value = value.split(":", 1)[0]
    return value.strip().strip("/")


def _allowed_hosts():
    configured = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
    values = configured.split(",") if configured else [os.environ.get("PUBLIC_HOST", "localhost")]

    hosts = []
    for item in values:
        host = _normalize_host(item)
        if host and host not in hosts:
            hosts.append(host)

    for fallback_host in ["localhost", "127.0.0.1", "[::1]"]:
        host = _normalize_host(fallback_host)
        if host not in hosts:
            hosts.append(host)

    return hosts


ALLOWED_HOSTS = _allowed_hosts()

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'App01.apps.App01Config',
]

_protocol = os.environ.get("PROTOCOL", "http")
_public_host = os.environ.get("PUBLIC_HOST", "localhost")
_public_port = os.environ.get("PUBLIC_PORT", "80")

CORS_ALLOWED_ORIGINS = os.environ.get(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    f"{_protocol}://{_public_host}:{_public_port}",
).split(",")

# Trust Nginx's forwarded headers (Django is behind a reverse proxy)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Required for CSRF to work when the site is served over HTTPS
CSRF_TRUSTED_ORIGINS = [f"{_protocol}://{_public_host}"]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aware_light_config_Django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "reactapp/build")]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aware_light_config_Django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.environ.get("DJANGO_STATIC_ROOT", "/app/staticfiles")
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "reactapp/build/static"),
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# PROJECT_ROOT/studies is the repo-root studies/ folder in both cases: in
# Docker it's reached via the /project bind mount, locally it's just the repo.
STORAGE_DIR = os.environ.get("DJANGO_STORAGE_DIR") or str(PROJECT_ROOT / "studies")
