#!/bin/sh
# Apply this deployment's generated passwords to the accounts that init_all.sql
# creates.
#
# Runs once, on an empty data directory, and alphabetically after init_all.sql so
# every account already exists. init_all.sql only ever uses CREATE USER IF NOT
# EXISTS, so the passwords set here are not reset by later restarts even though
# --init-file replays that file on every start.
#
# Both variables are generated by setup/deploy_config.py and written to .env, which
# docker compose passes to the mysql service. PARTICIPANT_DB_PASSWORD belongs to the
# accounts phones open the database with; ANDROID_SERVER_DB_PASSWORD belongs to the
# Android micro-server's own account, which is what performs every write on the
# webservice dataflow. They are separate secrets because the participant one is
# published to every phone in the study on the direct path, and the server's account
# may read the enrolment registry a phone's may not. Either one left unset keeps that
# account's seed password from init_all.sql.
set -e

apply() {
    mysql --protocol=socket -uroot -p"$MYSQL_ROOT_PASSWORD" <<SQL
$1
FLUSH PRIVILEGES;
SQL
}

if [ -z "$PARTICIPANT_DB_PASSWORD" ]; then
    echo "zz-participant-password: PARTICIPANT_DB_PASSWORD is unset; keeping the seed password." >&2
else
    apply "ALTER USER 'aware_android_participant'@'%' IDENTIFIED BY '${PARTICIPANT_DB_PASSWORD}';
ALTER USER 'aware_ios_participant'@'%' IDENTIFIED BY '${PARTICIPANT_DB_PASSWORD}';"
    echo "zz-participant-password: applied the generated participant password." >&2
fi

if [ -z "$ANDROID_SERVER_DB_PASSWORD" ]; then
    echo "zz-participant-password: ANDROID_SERVER_DB_PASSWORD is unset; keeping the seed password." >&2
else
    apply "ALTER USER 'aware_android_server'@'%' IDENTIFIED BY '${ANDROID_SERVER_DB_PASSWORD}';"
    echo "zz-participant-password: applied the generated Android server password." >&2
fi
