#!/bin/sh
# Apply this deployment's generated participant password to the accounts that
# init_all.sql creates.
#
# Runs once, on an empty data directory, and alphabetically after init_all.sql
# so both accounts already exist. init_all.sql only ever uses CREATE USER IF
# NOT EXISTS, so the password set here is not reset by later restarts even
# though --init-file replays that file on every start.
#
# PARTICIPANT_DB_PASSWORD is generated by setup/deploy_config.py and written to
# .env, which docker compose passes to the mysql service. When it is unset the
# seed password from init_all.sql is left in place.
set -e

if [ -z "$PARTICIPANT_DB_PASSWORD" ]; then
    echo "zz-participant-password: PARTICIPANT_DB_PASSWORD is unset; keeping the seed password." >&2
else
    mysql --protocol=socket -uroot -p"$MYSQL_ROOT_PASSWORD" <<SQL
ALTER USER 'aware_android_participant'@'%' IDENTIFIED BY '${PARTICIPANT_DB_PASSWORD}';
ALTER USER 'aware_ios_participant'@'%' IDENTIFIED BY '${PARTICIPANT_DB_PASSWORD}';
FLUSH PRIVILEGES;
SQL
    echo "zz-participant-password: applied the generated participant password." >&2
fi
